# docker-compose file for a microservice lists all containers the service needs. In this case, couchbase to store data

version: '3'

services:

  product-service:
    build: .
    ports:
      - 8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - couchbase
      - consul
    links:
      - couchbase
      - consul

  couchbase:
    build: ./couchbase
    ports:
      - 8091:8091
      - 27017:27017

  consul:
    build: ./consul
    ports:
      - 8500:8500

