# docker-compose file for a microservice lists all containers the service needs. In this case, couchbase to store data

version: '3'

services:

  product-service:
    build: .
    network_mode: bridge
    ports:
      - 8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - couchbase-product
    links:
      - couchbase-product
    external_links:
      - storeinfrastructure_consul_1

  couchbase-product:
    build: ./couchbase
    network_mode: bridge
    ports:
      - 8091:8091
#      - 27017:27017

