# hostname should match the couchbase host name for the environment. here it is local and

spring:
  profiles:
    active: dev
  application:
    name: product-service

---
spring:
  profiles: dev
  cloud:
    consul:
      host: localhost
      port: 8500

couchbase:
  bucket:
    name: products
    password: password
  bootstrap-hosts: localhost

---
spring:
  profiles: docker
  cloud:
    consul:
      host: storeinfrastructure_consul_1
      port: 8500
      discovery:
        preferIpAddress: true  # not using this flag makes consul use the container Id instead of ip and so breaks

couchbase:
  bucket:
    name: products
    password: password
  bootstrap-hosts: couchbase-product

